### PR TITLE
ES Modules

### LINKED ISSUE #136: ESModules
[ESModules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is the standard modules system for JavaScript.

In the web it is supported by all the major latest browsers but most importantly it is interpreted better by bundlers (like Webpack and Rollup) with a technique called Tree Shaking which leverages the static nature of ESModules to eliminate dead code branches.

Implementating it should be easy as

```diff
-exports.name = name
+export { name }
```

```diff
-var name = require('module').name 
+import { name } from './module'
```

This will solve: #65

### PR DESCRIPTION
**Pull request by iddan**
Resolves #136
 - Refactor code to use ES Modules
 - Replaced Browserify with Rollup
 - Updated ESLint
 - Formatted code with Prettier

### CODE REVIEW

**Comment by jgm** [comment]
Thanks for this!  I would have preferred to have the formatting changes separated from the substantive ones, as this is a big patch to review.  But okay. A few questions:

- Why is `test/spec.txt` modified?  It should not be.
- I didn't understand the commit "define both legacy code and new node friendly files."
- I noticed that the test was updated to work with older systems and run the "node friendly files"; I was worried that this might mean that it just runs the `dist/commonmark.js`, which isn't always updated.  It is nice to be able to run tests without always rebuilding that.

**Comment by iddan** [comment]
- The spec text was modified because I ran all the commands in the `Make` file. I'll revert it.
 - In the `package.json` there are two entries for the package: for CommonJS there is `main` and for ESModules there is `module`. It's a way to expose both interfaces.
 - I had to change the test to use the dist version as old versions of node can't run the new code. ESModules only work since Node.js 12 and the CI tests on many Node versions.

**Comment by jgm** [comment]
I don't like having the tests run the dist code: that means that we have to regenerate the dist code every time we test, and that isn't a good workflow.  (I prefer updating the dist only on releases, which makes individual commits smaller and easier to inspect.)

Is there an alternative?

**Comment by jgm** [comment]
I'm trying out your branch, and I find that `make dist` now gives an error. It seems that the Makefile is still using uglify to create the `.min.js` dist, while using `npm run build` for the `.js` version. Is that intentional?

Also about the `make dist` target: When I run `npm run build` it creates `dist/commonmark.js` with
```
> commonmark@0.29.1 build /Users/jgm/src/commonmark.js
> rollup -c
```
to stdout and
```
lib/index.js → dist/commonmark.js...
created dist/commonmark.js in 611ms
```
to stderr.  But when I run `npm run build > dist/commonmark.js` (as in the Makefile) I would have expected `dist/commonmark.js` to contain the stdout from `npm run build`, but it still creates `dist/commonmark.js` correctly.  Maybe the file is created after stdout stream is closed?  This is very weird.  But in any case, the `make dist` target no longer includes licensing information at the top of `dist/commonmark.js` as it did before.

**Comment by jgm** [comment]
Here's a fix for adding the license.
```
diff --git a/Makefile b/Makefile
index 84eef88..393f15b 100644
--- a/Makefile
+++ b/Makefile
@@ -4,6 +4,7 @@ BENCHINP?=bench/samples/README.md
 VERSION?=$(SPECVERSION)
 JSMODULES=$(wildcard lib/*.js)
 UGLIFYJS=node_modules/.bin/uglifyjs
+LICENSETEXT="/* commonmark $(VERSION) https://github.com/commonmark/commonmark.js @license BSD3 */"

 .PHONY: dingus dist test bench bench-detailed npm lint clean update-spec

@@ -13,8 +14,8 @@ lint:
 dist: dist/commonmark.js dist/commonmark.min.js

 dist/commonmark.js: lib/index.js ${JSMODULES}
-       echo '/* commonmark $(VERSION) https://github.com/CommonMark/commonmark.js @license BSD3 */' > $@
-       npm run build >> $@
+       npm run build
+       (echo $(LICENSETEXT) && cat $@) > $@.tmp  && mv $@.tmp $@
```

**Comment by jgm** [comment]
I've merged your changes into a new branch `esmodules`. And I've added some fixes.
Further changes should be made there.

**Comment by jgm** [comment]
Here's another issue. `make bench` fails.
```
node bench/bench.js bench/samples/README.md
(node:76272) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/jgm/src/commonmark.js/bench/bench.js:3
import benchmark from "benchmark";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
But if I change the type in package.json from "commonjs" to "module", then `make test` fails.

I'm also confused about the node documentation, which says:

> Experimental support for ECMAScript modules is enabled by default. Node.js will treat the following as ES modules when passed to node as the initial input, or when referenced by import statements within ES module code:

> Files ending in .mjs.

> Files ending in .js, or extensionless files, when the nearest parent package.json file contains a top-level field "type" with a value of "module".

Does this mean we should be using `.mjs` extension?

**Comment by jgm** [comment]
`bin/commonmark` also fails.
```
...lib/index.js:14
export { default as Node } from "./node.js";
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by jgm** [comment]
I was able to get everything working with node 6+ using `esm`, and I'd probably be okay with not supporting node < 6.  But I'm not sure this is the best approach.

**Comment by iddan** [comment]
Hey there, sorry for the late response. I think esm is a good approach. I’ll try to fix all your comments in the following days.

**Comment by jgm** [comment]
If esm is a good approach, then I've already fixed the issues noted above.

**Comment by yanz33** [comment]
> Resolves #136
> 
> * Refactor code to use ES Modules
> * Replaced Browserify with Rollup
> * Updated ESLint
> * Formatted code with Prettier

**Comment by iddan** [comment]
Resolved conflicts. Can this please be merged?

**Comment by jgm** [comment]
I'm confused about why there are now two PRs for this issue (this and #186, which has no comments to explain itself).  I'm also not quite sure about this change still, which is why I haven't merged it yet.

**Comment by jgm** [comment]
OK, I've merged these commits via my esmodules branch.

**Comment by jgm** [comment]
Everything is about ready to go for a new release, but I'm wondering if changes to the documentation are in order to explain how to use the esmodules api.

**Pull request closed without merging**
