### PR TITLE
Fix list tightness.

### PR DESCRIPTION
**Pull request by taku0**
According to the specification, blank lines in a block quote doesn't separate list items:
https://spec.commonmark.org/0.30/#example-320

Therefore, the following example should be tight:

```markdown
- > - a
  >
- b
```

The specification also say that link reference definitions can be children of list items when checking list tightness: https://spec.commonmark.org/0.30/#example-317

Therefore, the following example should be loose:

```
- [aaa]: /

  [bbb]: /
- b
```

This commit fixes those problems with the following strategy:

- Using source end position and start position of adjoining elements to check tightness. 
  This requires adjusting source end position of some block types to exclude trailing blank lines. This introduces an incompatible change to `sourcepos` property of `Node`. If this cannot be acceptable, I will add a field to `Node` to hold source position for list tightness.

- Delaying removal of link reference definitions until the entire document is parsed.

## Re: CONTRIBUTING.md

> Ensure that all tests pass (make test).

```
$ make test
...
723 tests passed, 0 failed.
```

> Use make lint to check for problems.

```
$ make lint
npm run lint

> commonmark@0.30.0 lint
> eslint .

```

> Ensure that performance has not been affected (make bench before and after the change).

`master`:

```
commonmark.js x 3,754 ops/sec ±0.96% (92 runs sampled)
showdown.js x 407 ops/sec ±1.36% (85 runs sampled)
marked.js x 1,652 ops/sec ±1.28% (90 runs sampled)
markdown-it x 3,680 ops/sec ±1.02% (90 runs sampled)
```

This branch:

```
commonmark.js x 3,756 ops/sec ±1.14% (91 runs sampled)
showdown.js x 422 ops/sec ±0.81% (88 runs sampled)
marked.js x 1,690 ops/sec ±1.03% (92 runs sampled)
markdown-it x 3,724 ops/sec ±0.99% (91 runs sampled)
```

### CODE REVIEW

**Comment by taku0** [comment]
`cmark` works well for the former example but not the latter example.

**Comment by taku0** [comment]
`cmark` fails to handle the following case while the `master` branch `commonmark.js` can handle it:

```markdown
- ***
  [aaa]: /

  bbb
- c
```

**Comment by taku0** [comment]
Is the following example tight or loose? The `master` branch handles it as loose while this branch handles it tight.

```markdown
- <pre>

- </pre>
- a
```

**Comment by jgm** [comment]
That last one should be loose I think.

**Comment by taku0** [comment]
Updated to exlucde trailing blank lines from HTML blocks when checking tightness.

This behaviour seems inconsistent with the fenced code block:

`````markdown
- ```
  the following blank line is a part of fenced code block. Therefore, not
  separates list item:

- aaa

* <pre>The current implementation trims trailing blank lines from HTML blocks.
  Therefore, the following line is **not** a part of HTML block, so it
  separates the list items:

* The HTML block ends together with its parent (list item).
* </pre>
  The preceding line starts a new HTML block, it also ends together with its
  parent.

-     Indented code blocks are explicitly stated to exclude trailling blank
      lines.  Therefore, the following line is not a part of indentated code
      block and separetes the list items:
      
- aaa

`````

Maybe we should update the spec to specify whether each block types contain trailing blank lines or not.

**Comment by jgm** [comment]
Ah.  I hadn't taken into account of the fact that the blank line belongs to the raw HTML block (which it does according to the spec).

The spec says: "A list is [loose](https://spec.commonmark.org/0.30/#loose) if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them."  So, this case isn't loose after all, and I guess this is a bug in the behavior of the reference implementation.

**Comment by taku0** [comment]
Fixed HTML blocks to include trailing blank lines. The previous example is now tight.

**Comment by taku0** [comment]
@jgm can this be merged? Please let me know if there is anything I should do to merge this pull request.

**Comment by jgm** [comment]
Sorry for the delay on this.  Can you briefly summarize the changes and their rationale?  It's a fairly big PR.

**Comment by jgm** [comment]
Thank you very much for that lucid and detailed explanation.

I believe that the reason I didn't use the "compare end line to start line of next block" method was that the closing line positions for indented code and lists included the blank lines following them.  For example:

```
 % bin/commonmark --sourcepos
1. a
   - b
   - c


2. d
<ol data-sourcepos="1:1-6:4">
<li data-sourcepos="1:1-5:0">
<p data-sourcepos="1:4-1:4">a</p>
<ul data-sourcepos="2:4-5:0">
<li data-sourcepos="2:4-2:6">b</li>
<li data-sourcepos="3:4-5:0">c</li>
</ul>
</li>
<li data-sourcepos="6:1-6:4">
<p data-sourcepos="6:4-6:4">d</p>
</li>
</ol>
```
Note that the inner list goes from lines 2-5, and the next item starts on 6, so this woldu be tight as judged by the "next line" test.

You say that you've modified the finalizers to produce more accurate end positions, which would fix the problem.  I saw this code for indented code blocks but didn't notice it for lists -- is it there?

Anyway, as long as this problem is dealt with, I agree that your approach is much cleaner!

Have you checked benchmarks and pathological tests to make sure that there are no bad effects?  I imagine that handling reference links at the end by walking the whole document might be *slightly* less performant than handling them in the finalizers, but I'm guessing the difference is miniscule.

**Review by Anagirotti — APPROVED** [review]

**Comment by taku0** [comment]
@jgm 

> You say that you've modified the finalizers to produce more accurate end positions, which would fix the problem. I saw this code for indented code blocks but didn't notice it for lists -- is it there?

It is adjusted in `finalize` method of `item` and `list` type.

The end position of a `item` is the end position of the last child if any. If the item is empty, the end position is the position after the marker and padding.
https://github.com/commonmark/commonmark.js/blob/d1d3d179d6726dfa52c3a7dc110482b14767fc66/lib/blocks.js#L356-L367

The end position of a `list` is the end position of the last item.
https://github.com/commonmark/commonmark.js/blob/d1d3d179d6726dfa52c3a7dc110482b14767fc66/lib/blocks.js#L301

Here is the output of `commonmark --sourcepos`:

```
$ bin/commonmark --sourcepos
1. a
   - b
   - c


2. d
<ol data-sourcepos="1:1-6:4">
<li data-sourcepos="1:1-3:6">
<p data-sourcepos="1:4-1:4">a</p>
<ul data-sourcepos="2:4-3:6">
<li data-sourcepos="2:4-2:6">b</li>
<li data-sourcepos="3:4-3:6">c</li>
</ul>
</li>
<li data-sourcepos="6:1-6:4">
<p data-sourcepos="6:4-6:4">d</p>
</li>
</ol>
```

> Have you checked benchmarks and pathological tests to make sure that there are no bad effects?

<details>
<summary><code>make test</code> <code>723 tests passed, 0 failed.</code> (click for full output)</summary>

```
$ make test
npm test

> commonmark@0.30.0 pretest
> npm run build


> commonmark@0.30.0 build
> rollup -c


lib/index.js → dist/commonmark.js, dist/commonmark.min.js...
created dist/commonmark.js, dist/commonmark.min.js in 2s

> commonmark@0.30.0 test
> node ./test/test

Spec tests [test/spec.txt]:
Tabs  ✓✓✓✓✓✓✓✓✓✓✓
Backslash escapes  ✓✓✓✓✓✓✓✓✓✓✓✓✓
Entity and numeric character references  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Precedence  ✓
Thematic breaks  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
ATX headings  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Setext headings  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Indented code blocks  ✓✓✓✓✓✓✓✓✓✓✓✓
Fenced code blocks  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
HTML blocks  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Link reference definitions  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Paragraphs  ✓✓✓✓✓✓✓✓
Blank lines  ✓
Block quotes  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
List items  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Lists  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Inlines  ✓
Code spans  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Emphasis and strong emphasis  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Links  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Images  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Autolinks  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Raw HTML  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Hard line breaks  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Soft line breaks  ✓✓
Textual content  ✓✓✓
Elapsed time: 34.399ms

Spec tests [test/smart_punct.txt]:
Smart punctuation  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Elapsed time: 0.709ms

Spec tests [test/regression.txt]:
Regression tests  ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
Elapsed time: 1.142ms

Pathological cases:
U+0000 in input ✓
  elapsed time: 0.18ms
alternate line endings ✓
  elapsed time: 0.05ms
nested strong emph 1000 deep ✓
  elapsed time: 17.393ms
nested strong emph 10000 deep ✓
  elapsed time: 104.974ms
1000 emph closers with no openers ✓
  elapsed time: 0.465ms
10000 emph closers with no openers ✓
  elapsed time: 7.528ms
1000 emph openers with no closers ✓
  elapsed time: 0.434ms
10000 emph openers with no closers ✓
  elapsed time: 6.858ms
1000 openers and closers multiple of 3 ✓
  elapsed time: 0.515ms
10000 openers and closers multiple of 3 ✓
  elapsed time: 6.11ms
1000 #172 ✓
  elapsed time: 1.372ms
10000 #172 ✓
  elapsed time: 30.178ms
1000 link closers with no openers ✓
  elapsed time: 0.318ms
10000 link closers with no openers ✓
  elapsed time: 6.703ms
1000 link openers with no closers ✓
  elapsed time: 0.402ms
10000 link openers with no closers ✓
  elapsed time: 7.793ms
1000 link openers and emph closers ✓
  elapsed time: 0.678ms
10000 link openers and emph closers ✓
  elapsed time: 16.744ms
1000 mismatched openers and closers ✓
  elapsed time: 0.81ms
10000 mismatched openers and closers ✓
  elapsed time: 22.765ms
1000 pattern [ (]( ✓
  elapsed time: 2.047ms
10000 pattern [ (]( ✓
  elapsed time: 27.861ms
nested brackets 1000 deep ✓
  elapsed time: 0.451ms
nested brackets 10000 deep ✓
  elapsed time: 19.995ms
nested block quote 1000 deep ✓
  elapsed time: 1.295ms
nested block quote 10000 deep ✓
  elapsed time: 27.169ms
[\\... 1000 deep ✓
  elapsed time: 12.591ms
[\\... 10000 deep ✓
  elapsed time: 1.11ms
10 backslashes in unclosed link title ✓
  elapsed time: 0.137ms
100 backslashes in unclosed link title ✓
  elapsed time: 0.038ms
1000 backslashes in unclosed link title ✓
  elapsed time: 0.132ms

723 tests passed, 0 failed.
```

</details>

> I imagine that handling reference links at the end by walking the whole document might be slightly less performant than handling them in the finalizers, but I'm guessing the difference is miniscule. (EDIT: I'd also expect some increase in performance from the more streamlined tight/loose checking.)

Performance impact isn't significant:

`master` branch:

```
$ make bench
node bench/bench.js bench/samples/README.md
commonmark.js x 3,931 ops/sec ±0.78% (92 runs sampled)
showdown.js x 442 ops/sec ±0.71% (91 runs sampled)
marked.js x 1,709 ops/sec ±0.82% (92 runs sampled)
markdown-it x 3,933 ops/sec ±0.69% (94 runs sampled)
```

This branch:

```
$ make bench
node bench/bench.js bench/samples/README.md
commonmark.js x 3,974 ops/sec ±1.25% (90 runs sampled)
showdown.js x 441 ops/sec ±0.54% (91 runs sampled)
marked.js x 1,715 ops/sec ±0.83% (93 runs sampled)
markdown-it x 3,919 ops/sec ±0.65% (94 runs sampled)
```

**Comment by vassudanagunta** [comment]
I'm not sure if the point I'm about to make is moot because CommonMark is already too far gone down this path, in which case taking it to its logical conclusion, as this PR does, may be the smart thing to do.

*I think it is a mistake to determine list "looseness" based on blank lines in the plain text, because such blank lines are often an artifact of syntax, not semantics.*

For example, the following two lists are semantically identical, but because of an artifact of syntax, CommonMark considers the first loose and the second tight:


``` markdown
- item one
- item two
  
  Loose Lists Sink Ships
  ======================
  more text
- item three
```

``` markdown
- item one
- item two
  # How Not to Run a Tight List
  more text
- item three
```

### What is a tight list intuitively?

A tight list is a list that can be ***readably*** rendered with no additional vertical whitespace beyond regular intra-paragraph line spacing. 

### What, then, is a tight list semantically?

A tight list is a list all of whose items have only inline text content. They do not contain paragraphs or any other block content, with one exception: a nested list which itself is tight. 

Because of the list markers, such list items do not need the vertical margin that usually separates paragraphs. In addition, because the list item does not contain a sequence of two or more blocks beyond the one exception, it won't have internal vertical whitespace that would necessitate commensurate whitespace above and below it to effect a more readable and aesthetic visual grouping of elements.

Thus if we could go back in time, I'd push the following for the CommonMark spec: 

- A list items whose content is a single block of text is parsed as a list item with *inline content*.
- A list items whose content is a single block of text followed by a single nested list is parsed as a list item with *inline content followed by a single nested list*.
- In all other cases, the list item's content is parsed as a sequence of blocks.
- The AST would reflect this. How it is rendered would be up to the renderer, but the natural rendering would be exactly as one would expect.

### Gruber got this both right and wrong

So while Gruber's Markdown produces the same result as CommonMark for the first list above, it yields something entirely different for the second:

``` html
<ul>
  <li>item one</li>
  <li>item two
    # How Not to Run a Tight List
    more text</li>
  <li>item three</li>
</ul>
```

I haven't looked as his code, but based on empirical data, it looks like Gruber parses list item content this way:

- If it has a blank line, it is parsed as nested blocks.
- If it does not have a blank line, it is parsed as inline content.

The end result puts Gruber's interpretation somewhere between CommonMark's and mine.  It's consistent with my definition of tightness as it ties tightness strictly to whether the list item contains inlines or blocks.  But like CommonMark, its behavior is governed by the presence or absence of blank lines. The result is a bit backward, as seen above: the lack of blank line predetermines that the content is inline. Thus what would otherwise be seen as two paragraphs separated by a heading is not.  It violates CommonMark's [principle of uniformity](https://spec.commonmark.org/0.30/#principle-of-uniformity).

### Back to the PR

Let's pretend that I am right. Is the right thing to do cutting losses? Or doubling down?

Or is there a way to steer CommonMark's take closer to what I propose without breaking anything but crazy corner cases?

Or, maybe, again pretending that I'm right, correcting this should be left to new formats such as djot.

**Comment by vassudanagunta** [comment]
### Addendum

The following, per CommonMark, are a tight list and a loose list:


```
- > - a
- b
```

```
- > - a

- b
```

But because the first item in both cases contains a nested block, there is no visual difference in typical HTML renderings. [You can see this](https://babelmark.github.io/?text=%23+loose+list%0A%0A-+%3E+-+a%0A%0A-+b%0A%0A%23+nominally+tight+list%0A%0A-+%3E+-+a%0A-+b%0A) when comparing the rendering of one against the other by any CommonMark compliant renders, as well as comparing to the rendering of those, like Pandoc, that appear to follow my definition. 

The only difference is in the details of the underlying HTML, which will only matter if you target that difference with CSS or Javascript.

**Comment by jgm** [comment]
@vassudanagunta this larger discussion doesn't really belong in this PR.
This PR fixes a problem in the javascript parser, and does it well.  Your point belongs in a discussion of the spec.

**Comment by jgm** [comment]
@taku0 this is great.  You've not only dramatically simplified the tight/list detection, and fixed a bug, you've also improved the accuracy of source positions.  Thank you very much for the patch and the clear explanations.

**Comment by vassudanagunta** [comment]
sorry @jgm. It wasn't obvious to me that this was a no-brainer change.

**Comment by taku0** [comment]
Thank you for merging. I will port this to `cmark` soon.

**Pull request merged**
