### PR TITLE
dingus: add dependency version requirements

### PR DESCRIPTION
**Pull request by vassudanagunta**
Dingus was rendering incorrectly with Bootstrap 4. Added a bower.json
which requires Bootstrap, jQuery and Lodash with major version equal
to what's currently live. Likewise the minimum patch version.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks! Can I suggest bumping up the lodash version to the latest?
There's a security advisory here: https://github.com/oncletom/crx/issues/89

**Comment by vassudanagunta** [comment]
Done! I updated the requirement to match `package.json` of `commonmark.js`.

Are you not concerned with incompatibilities that might be introduced with major version changes, i.e. `>=4.17.11` as opposed to `^4.17.11`?

**Comment by jgm** [comment]
Indeed.  Let's change to using `^`.  I've updated package.json.

**Comment by vassudanagunta** [comment]
done!

**Comment by jgm** [comment]
Thank you!

**Pull request merged**
